// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PBTest.proto

package proto.test.example;

public final class PBTestProtos {
  private PBTestProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PBTestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // optional .proto.test.PBTest.Corpus corpus = 4 [default = WEB];
    /**
     * <code>optional .proto.test.PBTest.Corpus corpus = 4 [default = WEB];</code>
     */
    boolean hasCorpus();
    /**
     * <code>optional .proto.test.PBTest.Corpus corpus = 4 [default = WEB];</code>
     */
    proto.test.example.PBTestProtos.PBTest.Corpus getCorpus();

    // repeated .proto.test.PBTest.Result result = 5;
    /**
     * <code>repeated .proto.test.PBTest.Result result = 5;</code>
     */
    java.util.List<proto.test.example.PBTestProtos.PBTest.Result> 
        getResultList();
    /**
     * <code>repeated .proto.test.PBTest.Result result = 5;</code>
     */
    proto.test.example.PBTestProtos.PBTest.Result getResult(int index);
    /**
     * <code>repeated .proto.test.PBTest.Result result = 5;</code>
     */
    int getResultCount();
    /**
     * <code>repeated .proto.test.PBTest.Result result = 5;</code>
     */
    java.util.List<? extends proto.test.example.PBTestProtos.PBTest.ResultOrBuilder> 
        getResultOrBuilderList();
    /**
     * <code>repeated .proto.test.PBTest.Result result = 5;</code>
     */
    proto.test.example.PBTestProtos.PBTest.ResultOrBuilder getResultOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.test.PBTest}
   */
  public static final class PBTest extends
      com.google.protobuf.GeneratedMessage
      implements PBTestOrBuilder {
    // Use PBTest.newBuilder() to construct.
    private PBTest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PBTest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PBTest defaultInstance;
    public static PBTest getDefaultInstance() {
      return defaultInstance;
    }

    public PBTest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PBTest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();
              proto.test.example.PBTestProtos.PBTest.Corpus value = proto.test.example.PBTestProtos.PBTest.Corpus.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(4, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                corpus_ = value;
              }
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                result_ = new java.util.ArrayList<proto.test.example.PBTestProtos.PBTest.Result>();
                mutable_bitField0_ |= 0x00000004;
              }
              result_.add(input.readMessage(proto.test.example.PBTestProtos.PBTest.Result.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          result_ = java.util.Collections.unmodifiableList(result_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.test.example.PBTestProtos.internal_static_proto_test_PBTest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.test.example.PBTestProtos.internal_static_proto_test_PBTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.test.example.PBTestProtos.PBTest.class, proto.test.example.PBTestProtos.PBTest.Builder.class);
    }

    public static com.google.protobuf.Parser<PBTest> PARSER =
        new com.google.protobuf.AbstractParser<PBTest>() {
      public PBTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PBTest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PBTest> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code proto.test.PBTest.Corpus}
     *
     * <pre>
     *枚举类型测试
     * </pre>
     */
    public enum Corpus
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNIVERAL = 0;</code>
       */
      UNIVERAL(0, 0),
      /**
       * <code>WEB = 1;</code>
       */
      WEB(1, 1),
      /**
       * <code>IMAGES = 2;</code>
       */
      IMAGES(2, 2),
      /**
       * <code>LOCAL = 3;</code>
       */
      LOCAL(3, 3),
      /**
       * <code>NEWS = 4;</code>
       */
      NEWS(4, 4),
      /**
       * <code>PRODUCTS = 5;</code>
       */
      PRODUCTS(5, 5),
      /**
       * <code>VIDEO = 6;</code>
       */
      VIDEO(6, 6),
      ;

      /**
       * <code>UNIVERAL = 0;</code>
       */
      public static final int UNIVERAL_VALUE = 0;
      /**
       * <code>WEB = 1;</code>
       */
      public static final int WEB_VALUE = 1;
      /**
       * <code>IMAGES = 2;</code>
       */
      public static final int IMAGES_VALUE = 2;
      /**
       * <code>LOCAL = 3;</code>
       */
      public static final int LOCAL_VALUE = 3;
      /**
       * <code>NEWS = 4;</code>
       */
      public static final int NEWS_VALUE = 4;
      /**
       * <code>PRODUCTS = 5;</code>
       */
      public static final int PRODUCTS_VALUE = 5;
      /**
       * <code>VIDEO = 6;</code>
       */
      public static final int VIDEO_VALUE = 6;


      public final int getNumber() { return value; }

      public static Corpus valueOf(int value) {
        switch (value) {
          case 0: return UNIVERAL;
          case 1: return WEB;
          case 2: return IMAGES;
          case 3: return LOCAL;
          case 4: return NEWS;
          case 5: return PRODUCTS;
          case 6: return VIDEO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Corpus>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Corpus>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Corpus>() {
              public Corpus findValueByNumber(int number) {
                return Corpus.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.test.example.PBTestProtos.PBTest.getDescriptor().getEnumTypes().get(0);
      }

      private static final Corpus[] VALUES = values();

      public static Corpus valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Corpus(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.test.PBTest.Corpus)
    }

    public interface ResultOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // required string url = 1;
      /**
       * <code>required string url = 1;</code>
       */
      boolean hasUrl();
      /**
       * <code>required string url = 1;</code>
       */
      java.lang.String getUrl();
      /**
       * <code>required string url = 1;</code>
       */
      com.google.protobuf.ByteString
          getUrlBytes();
    }
    /**
     * Protobuf type {@code proto.test.PBTest.Result}
     */
    public static final class Result extends
        com.google.protobuf.GeneratedMessage
        implements ResultOrBuilder {
      // Use Result.newBuilder() to construct.
      private Result(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Result(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Result defaultInstance;
      public static Result getDefaultInstance() {
        return defaultInstance;
      }

      public Result getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Result(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                url_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.test.example.PBTestProtos.internal_static_proto_test_PBTest_Result_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.test.example.PBTestProtos.internal_static_proto_test_PBTest_Result_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.test.example.PBTestProtos.PBTest.Result.class, proto.test.example.PBTestProtos.PBTest.Result.Builder.class);
      }

      public static com.google.protobuf.Parser<Result> PARSER =
          new com.google.protobuf.AbstractParser<Result>() {
        public Result parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Result(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Result> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // required string url = 1;
      public static final int URL_FIELD_NUMBER = 1;
      private java.lang.Object url_;
      /**
       * <code>required string url = 1;</code>
       */
      public boolean hasUrl() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string url = 1;</code>
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            url_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string url = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        url_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        if (!hasUrl()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getUrlBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getUrlBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static proto.test.example.PBTestProtos.PBTest.Result parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.test.example.PBTestProtos.PBTest.Result parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.test.example.PBTestProtos.PBTest.Result parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.test.example.PBTestProtos.PBTest.Result parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.test.example.PBTestProtos.PBTest.Result parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static proto.test.example.PBTestProtos.PBTest.Result parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static proto.test.example.PBTestProtos.PBTest.Result parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static proto.test.example.PBTestProtos.PBTest.Result parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static proto.test.example.PBTestProtos.PBTest.Result parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static proto.test.example.PBTestProtos.PBTest.Result parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(proto.test.example.PBTestProtos.PBTest.Result prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code proto.test.PBTest.Result}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements proto.test.example.PBTestProtos.PBTest.ResultOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return proto.test.example.PBTestProtos.internal_static_proto_test_PBTest_Result_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return proto.test.example.PBTestProtos.internal_static_proto_test_PBTest_Result_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  proto.test.example.PBTestProtos.PBTest.Result.class, proto.test.example.PBTestProtos.PBTest.Result.Builder.class);
        }

        // Construct using proto.test.example.PBTestProtos.PBTest.Result.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          url_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return proto.test.example.PBTestProtos.internal_static_proto_test_PBTest_Result_descriptor;
        }

        public proto.test.example.PBTestProtos.PBTest.Result getDefaultInstanceForType() {
          return proto.test.example.PBTestProtos.PBTest.Result.getDefaultInstance();
        }

        public proto.test.example.PBTestProtos.PBTest.Result build() {
          proto.test.example.PBTestProtos.PBTest.Result result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public proto.test.example.PBTestProtos.PBTest.Result buildPartial() {
          proto.test.example.PBTestProtos.PBTest.Result result = new proto.test.example.PBTestProtos.PBTest.Result(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.url_ = url_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof proto.test.example.PBTestProtos.PBTest.Result) {
            return mergeFrom((proto.test.example.PBTestProtos.PBTest.Result)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(proto.test.example.PBTestProtos.PBTest.Result other) {
          if (other == proto.test.example.PBTestProtos.PBTest.Result.getDefaultInstance()) return this;
          if (other.hasUrl()) {
            bitField0_ |= 0x00000001;
            url_ = other.url_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasUrl()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          proto.test.example.PBTestProtos.PBTest.Result parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (proto.test.example.PBTestProtos.PBTest.Result) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // required string url = 1;
        private java.lang.Object url_ = "";
        /**
         * <code>required string url = 1;</code>
         */
        public boolean hasUrl() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string url = 1;</code>
         */
        public java.lang.String getUrl() {
          java.lang.Object ref = url_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            url_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string url = 1;</code>
         */
        public com.google.protobuf.ByteString
            getUrlBytes() {
          java.lang.Object ref = url_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            url_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string url = 1;</code>
         */
        public Builder setUrl(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          url_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string url = 1;</code>
         */
        public Builder clearUrl() {
          bitField0_ = (bitField0_ & ~0x00000001);
          url_ = getDefaultInstance().getUrl();
          onChanged();
          return this;
        }
        /**
         * <code>required string url = 1;</code>
         */
        public Builder setUrlBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          url_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:proto.test.PBTest.Result)
      }

      static {
        defaultInstance = new Result(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:proto.test.PBTest.Result)
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional .proto.test.PBTest.Corpus corpus = 4 [default = WEB];
    public static final int CORPUS_FIELD_NUMBER = 4;
    private proto.test.example.PBTestProtos.PBTest.Corpus corpus_;
    /**
     * <code>optional .proto.test.PBTest.Corpus corpus = 4 [default = WEB];</code>
     */
    public boolean hasCorpus() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .proto.test.PBTest.Corpus corpus = 4 [default = WEB];</code>
     */
    public proto.test.example.PBTestProtos.PBTest.Corpus getCorpus() {
      return corpus_;
    }

    // repeated .proto.test.PBTest.Result result = 5;
    public static final int RESULT_FIELD_NUMBER = 5;
    private java.util.List<proto.test.example.PBTestProtos.PBTest.Result> result_;
    /**
     * <code>repeated .proto.test.PBTest.Result result = 5;</code>
     */
    public java.util.List<proto.test.example.PBTestProtos.PBTest.Result> getResultList() {
      return result_;
    }
    /**
     * <code>repeated .proto.test.PBTest.Result result = 5;</code>
     */
    public java.util.List<? extends proto.test.example.PBTestProtos.PBTest.ResultOrBuilder> 
        getResultOrBuilderList() {
      return result_;
    }
    /**
     * <code>repeated .proto.test.PBTest.Result result = 5;</code>
     */
    public int getResultCount() {
      return result_.size();
    }
    /**
     * <code>repeated .proto.test.PBTest.Result result = 5;</code>
     */
    public proto.test.example.PBTestProtos.PBTest.Result getResult(int index) {
      return result_.get(index);
    }
    /**
     * <code>repeated .proto.test.PBTest.Result result = 5;</code>
     */
    public proto.test.example.PBTestProtos.PBTest.ResultOrBuilder getResultOrBuilder(
        int index) {
      return result_.get(index);
    }

    private void initFields() {
      id_ = 0;
      corpus_ = proto.test.example.PBTestProtos.PBTest.Corpus.WEB;
      result_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getResultCount(); i++) {
        if (!getResult(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(4, corpus_.getNumber());
      }
      for (int i = 0; i < result_.size(); i++) {
        output.writeMessage(5, result_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, corpus_.getNumber());
      }
      for (int i = 0; i < result_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, result_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.test.example.PBTestProtos.PBTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.test.example.PBTestProtos.PBTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.test.example.PBTestProtos.PBTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.test.example.PBTestProtos.PBTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.test.example.PBTestProtos.PBTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.test.example.PBTestProtos.PBTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.test.example.PBTestProtos.PBTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.test.example.PBTestProtos.PBTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.test.example.PBTestProtos.PBTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.test.example.PBTestProtos.PBTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.test.example.PBTestProtos.PBTest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.test.PBTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.test.example.PBTestProtos.PBTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.test.example.PBTestProtos.internal_static_proto_test_PBTest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.test.example.PBTestProtos.internal_static_proto_test_PBTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.test.example.PBTestProtos.PBTest.class, proto.test.example.PBTestProtos.PBTest.Builder.class);
      }

      // Construct using proto.test.example.PBTestProtos.PBTest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getResultFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        corpus_ = proto.test.example.PBTestProtos.PBTest.Corpus.WEB;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          resultBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.test.example.PBTestProtos.internal_static_proto_test_PBTest_descriptor;
      }

      public proto.test.example.PBTestProtos.PBTest getDefaultInstanceForType() {
        return proto.test.example.PBTestProtos.PBTest.getDefaultInstance();
      }

      public proto.test.example.PBTestProtos.PBTest build() {
        proto.test.example.PBTestProtos.PBTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.test.example.PBTestProtos.PBTest buildPartial() {
        proto.test.example.PBTestProtos.PBTest result = new proto.test.example.PBTestProtos.PBTest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.corpus_ = corpus_;
        if (resultBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            result_ = java.util.Collections.unmodifiableList(result_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.result_ = result_;
        } else {
          result.result_ = resultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.test.example.PBTestProtos.PBTest) {
          return mergeFrom((proto.test.example.PBTestProtos.PBTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.test.example.PBTestProtos.PBTest other) {
        if (other == proto.test.example.PBTestProtos.PBTest.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCorpus()) {
          setCorpus(other.getCorpus());
        }
        if (resultBuilder_ == null) {
          if (!other.result_.isEmpty()) {
            if (result_.isEmpty()) {
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureResultIsMutable();
              result_.addAll(other.result_);
            }
            onChanged();
          }
        } else {
          if (!other.result_.isEmpty()) {
            if (resultBuilder_.isEmpty()) {
              resultBuilder_.dispose();
              resultBuilder_ = null;
              result_ = other.result_;
              bitField0_ = (bitField0_ & ~0x00000004);
              resultBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getResultFieldBuilder() : null;
            } else {
              resultBuilder_.addAllMessages(other.result_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        for (int i = 0; i < getResultCount(); i++) {
          if (!getResult(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.test.example.PBTestProtos.PBTest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.test.example.PBTestProtos.PBTest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional .proto.test.PBTest.Corpus corpus = 4 [default = WEB];
      private proto.test.example.PBTestProtos.PBTest.Corpus corpus_ = proto.test.example.PBTestProtos.PBTest.Corpus.WEB;
      /**
       * <code>optional .proto.test.PBTest.Corpus corpus = 4 [default = WEB];</code>
       */
      public boolean hasCorpus() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .proto.test.PBTest.Corpus corpus = 4 [default = WEB];</code>
       */
      public proto.test.example.PBTestProtos.PBTest.Corpus getCorpus() {
        return corpus_;
      }
      /**
       * <code>optional .proto.test.PBTest.Corpus corpus = 4 [default = WEB];</code>
       */
      public Builder setCorpus(proto.test.example.PBTestProtos.PBTest.Corpus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        corpus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .proto.test.PBTest.Corpus corpus = 4 [default = WEB];</code>
       */
      public Builder clearCorpus() {
        bitField0_ = (bitField0_ & ~0x00000002);
        corpus_ = proto.test.example.PBTestProtos.PBTest.Corpus.WEB;
        onChanged();
        return this;
      }

      // repeated .proto.test.PBTest.Result result = 5;
      private java.util.List<proto.test.example.PBTestProtos.PBTest.Result> result_ =
        java.util.Collections.emptyList();
      private void ensureResultIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          result_ = new java.util.ArrayList<proto.test.example.PBTestProtos.PBTest.Result>(result_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          proto.test.example.PBTestProtos.PBTest.Result, proto.test.example.PBTestProtos.PBTest.Result.Builder, proto.test.example.PBTestProtos.PBTest.ResultOrBuilder> resultBuilder_;

      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public java.util.List<proto.test.example.PBTestProtos.PBTest.Result> getResultList() {
        if (resultBuilder_ == null) {
          return java.util.Collections.unmodifiableList(result_);
        } else {
          return resultBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public int getResultCount() {
        if (resultBuilder_ == null) {
          return result_.size();
        } else {
          return resultBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public proto.test.example.PBTestProtos.PBTest.Result getResult(int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);
        } else {
          return resultBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public Builder setResult(
          int index, proto.test.example.PBTestProtos.PBTest.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.set(index, value);
          onChanged();
        } else {
          resultBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public Builder setResult(
          int index, proto.test.example.PBTestProtos.PBTest.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.set(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public Builder addResult(proto.test.example.PBTestProtos.PBTest.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(value);
          onChanged();
        } else {
          resultBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public Builder addResult(
          int index, proto.test.example.PBTestProtos.PBTest.Result value) {
        if (resultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureResultIsMutable();
          result_.add(index, value);
          onChanged();
        } else {
          resultBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public Builder addResult(
          proto.test.example.PBTestProtos.PBTest.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public Builder addResult(
          int index, proto.test.example.PBTestProtos.PBTest.Result.Builder builderForValue) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.add(index, builderForValue.build());
          onChanged();
        } else {
          resultBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public Builder addAllResult(
          java.lang.Iterable<? extends proto.test.example.PBTestProtos.PBTest.Result> values) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          super.addAll(values, result_);
          onChanged();
        } else {
          resultBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public Builder clearResult() {
        if (resultBuilder_ == null) {
          result_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          resultBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public Builder removeResult(int index) {
        if (resultBuilder_ == null) {
          ensureResultIsMutable();
          result_.remove(index);
          onChanged();
        } else {
          resultBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public proto.test.example.PBTestProtos.PBTest.Result.Builder getResultBuilder(
          int index) {
        return getResultFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public proto.test.example.PBTestProtos.PBTest.ResultOrBuilder getResultOrBuilder(
          int index) {
        if (resultBuilder_ == null) {
          return result_.get(index);  } else {
          return resultBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public java.util.List<? extends proto.test.example.PBTestProtos.PBTest.ResultOrBuilder> 
           getResultOrBuilderList() {
        if (resultBuilder_ != null) {
          return resultBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(result_);
        }
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public proto.test.example.PBTestProtos.PBTest.Result.Builder addResultBuilder() {
        return getResultFieldBuilder().addBuilder(
            proto.test.example.PBTestProtos.PBTest.Result.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public proto.test.example.PBTestProtos.PBTest.Result.Builder addResultBuilder(
          int index) {
        return getResultFieldBuilder().addBuilder(
            index, proto.test.example.PBTestProtos.PBTest.Result.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.test.PBTest.Result result = 5;</code>
       */
      public java.util.List<proto.test.example.PBTestProtos.PBTest.Result.Builder> 
           getResultBuilderList() {
        return getResultFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          proto.test.example.PBTestProtos.PBTest.Result, proto.test.example.PBTestProtos.PBTest.Result.Builder, proto.test.example.PBTestProtos.PBTest.ResultOrBuilder> 
          getResultFieldBuilder() {
        if (resultBuilder_ == null) {
          resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              proto.test.example.PBTestProtos.PBTest.Result, proto.test.example.PBTestProtos.PBTest.Result.Builder, proto.test.example.PBTestProtos.PBTest.ResultOrBuilder>(
                  result_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          result_ = null;
        }
        return resultBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:proto.test.PBTest)
    }

    static {
      defaultInstance = new PBTest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.test.PBTest)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_test_PBTest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_test_PBTest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_test_PBTest_Result_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_test_PBTest_Result_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014PBTest.proto\022\nproto.test\"\341\001\n\006PBTest\022\n\n" +
      "\002id\030\001 \002(\005\022.\n\006corpus\030\004 \001(\0162\031.proto.test.P" +
      "BTest.Corpus:\003WEB\022)\n\006result\030\005 \003(\0132\031.prot" +
      "o.test.PBTest.Result\032\025\n\006Result\022\013\n\003url\030\001 " +
      "\002(\t\"Y\n\006Corpus\022\014\n\010UNIVERAL\020\000\022\007\n\003WEB\020\001\022\n\n\006" +
      "IMAGES\020\002\022\t\n\005LOCAL\020\003\022\010\n\004NEWS\020\004\022\014\n\010PRODUCT" +
      "S\020\005\022\t\n\005VIDEO\020\006B\"\n\022proto.test.exampleB\014PB" +
      "TestProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_test_PBTest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_test_PBTest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_test_PBTest_descriptor,
              new java.lang.String[] { "Id", "Corpus", "Result", });
          internal_static_proto_test_PBTest_Result_descriptor =
            internal_static_proto_test_PBTest_descriptor.getNestedTypes().get(0);
          internal_static_proto_test_PBTest_Result_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_test_PBTest_Result_descriptor,
              new java.lang.String[] { "Url", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
